spring.main.headless=false
spring.application.name=cotan-avaliacao-desempenho
spring.main.web-application-type=none
cotan.avaliacao.sqlite.path=${user.home}/.CotanAvaliacaoDesempenho/data/avaliacao.db
