spring.main.headless=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=false
cotan.avaliacao.sqlite.path=${user.home}/.CotanFx/data/avaliacao.db
